# A minimal tmux config to get started e.g. on a remote server

# Prefer tmux terminfo when available; fall back if remote box is old
set -g default-terminal "tmux-256color"

set -g extended-keys-format csi-u # Enable support for extended (modified) keys, e.g. Shift+Arrow keys, Ctrl+Arrow keys, etc.

set -g mode-keys vi # Enable vi-mode
set -g status-keys emacs # emacs key bindings in tmux command prompt (prefix + :) are better than vi keys, even for vim users
set -g mouse on

# Better copy-mode ergonomics with mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

bind r source-file ~/.tmux.conf \; display "reloaded"

set -sg escape-time 10 # Don't delay the ESC key too much
set-option -g history-limit 5000
set -g base-index 1
set -g allow-rename off
set -g focus-events on

set -g allow-passthrough on.
