cask '1password'
cask 'alfred'
cask 'firefox'
cask 'google-chrome'
cask 'hammerspoon'
cask 'iina' # Video player
cask 'karabiner-elements'
cask 'nikitabobko/tap/aerospace'
cask 'spotify'
cask 'stats' # https://github.com/exelban/stats
cask 'tableplus'
cask 'xnviewmp' # Image viewer
cask 'thaw'

# AI
cask 'codex'
cask 'copilot-cli'
brew 'gemini-cli'

# Manuall install needed because of --no-quarantine
# brew 'glance-chamburr' # QuickLook collection https://github.com/chamburr/glance
# brew install --no-quarantine glance-chamburr
