# List all available commands
nix-default:
  just --list

# Apply current macOS configuration
nix-darwin-rebuild:
  sudo darwin-rebuild switch --flake ~/.config/nix#simple

# Search nix packages
nix-search QUERY:
  nix search nixpkgs {{QUERY}}
