# List all available commands
nix-default:
  just --list

# Apply current macOS configuration
nix-darwin-rebuild:
  sudo darwin-rebuild switch --flake ~/.config/nix#simple

# Update all flake inputs and apply current macOS configuration
nix-update-all:
  nix --extra-experimental-features "nix-command flakes" flake update --flake ~/.config/nix
  just nix-darwin-rebuild
  just nix-system-packages-json

# Search nix packages
nix-search QUERY:
  nix search nixpkgs {{QUERY}}

# Export system packages and versions as JSON
nix-system-packages-json OUTPUT_PATH="~/.config/nix/system-packages.json":
  ~/.config/nix/export_system_packages_json.sh {{OUTPUT_PATH}}
