# List all available commands
nix-default:
  just --list

# All CI tasks for nix
nix-ci: nix-check

# Check the nix flake
nix-check:
  nix flake check ./private_dot_config/nix --extra-experimental-features 'nix-command flakes'

# Apply current macOS configuration
nix-darwin-rebuild:
  sudo darwin-rebuild switch --flake ~/.config/nix#simple

# Update all flake inputs and apply current macOS configuration
nix-update-all:
  nix --extra-experimental-features "nix-command flakes" flake update --flake ~/.config/nix
  just nix-darwin-rebuild
  just nix-system-packages-json
  chezmoi add ~/.config/nix/flake.lock

# Update only nixpkgs-unstable flake input and apply current macOS configuration
nix-update-nixpkgs-unstable:
  nix --extra-experimental-features "nix-command flakes" flake update nixpkgs-unstable --flake ~/.config/nix
  just nix-darwin-rebuild
  just nix-system-packages-json
  chezmoi add ~/.config/nix/flake.lock

# Search nix packages
nix-search QUERY:
  nix search nixpkgs {{QUERY}}

# Export system packages and versions as JSON
nix-system-packages-json OUTPUT_PATH="~/.config/nix/system-packages.json":
  ~/.config/nix/export_system_packages_json.sh {{OUTPUT_PATH}}
  chezmoi add ~/.config/nix/system-packages.json
