# All CI tasks for karabiner
karabiner-ci: karabiner-check karabiner-generate

# Check karabiner TypeScript
karabiner-check:
  cd private_dot_config/private_karabiner && deno fmt --check karabiner.ts deno.json && deno check karabiner.ts

# Generate the karabiner.json file from the karabiner.ts file
karabiner-generate:
  cd private_dot_config/private_karabiner && deno task karabiner-generate
