# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[mgr]
prepend_keymap = [
  { on = ["g", "?"], run = "help", desc = "Open help" },

  { on = "<C-p>", run = 'shell -- qlmanage -p "$@"', desc = "Preview the selected file(s) in Quick Look" },
  { on = "<C-o>", run = "shell --confirm 'open .'", desc = "Open the current directory in Finder" },

  { on = "f", run = "plugin fzf", desc = "Select with fzf" },

  # Plugin: jump-to-char
  { on = "F", run = "plugin jump-to-char", desc = "Jump to char" },

  # Plugin: bunny (fuzzy bookmark manager)
  { on = "u", run = "plugin bunny", desc = "Start bunny.yazi" },
  { on = "U", run = "plugin bunny fuzzy", desc = "Start bunny.yazi fuzzy search" },

  # Plugin: toggle-pane
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },

  # Plugin: duckdb
  { on = "H", run = "plugin duckdb -1", desc = "Scroll one column to the left" },
  { on = "L", run = "plugin duckdb +1", desc = "Scroll one column to the right" },
  { on = ["g", "o"], run = "plugin duckdb -open", desc = "open with duckdb" },
  { on = ["g", "u"], run = "plugin duckdb -ui", desc = "open with duckdb ui" },

  # Plugin: lazygit
  { on = ["g", "l"], run = "plugin lazygit", desc = "Open Lazygit" },

  # Plugin: what-size
  { on = ["p", "s"], run = "plugin what-size", desc = "Open what-size" },
]

[input]
prepend_keymap = [
  { on = ["g", "?"], run = "help", desc = "Open help" },
]
