# Plugins: git
[[mgr.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'
desc = "Preview the selected file(s) in Quick Look"

[[mgr.prepend_keymap]]
on = "<C-o>"
run = "shell --confirm 'open .'"
desc = "Open the current directory in Finder"

# Plugins: jump-to-char
[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"
