"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# style = "fg:color_fg1 bg:color_aqua"
format = """
[ ](bg:color_blue fg:color_blue)\
$directory\
[](bg:color_aqua fg:color_blue)\
[ ](bg:color_aqua)\
$git_branch\
$git_status\
$git_metrics\
$hg_branch\
$fossil_branch\
$vcsh\
[ ](bg:color_aqua)\
[](fg:color_aqua)\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg1 = '#fbf1c7'
color_fg2 = '#3c3836'
color_bg1 = '#3c3836'
color_bg2 = '#fbf1c7'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
style = "bg:color_blue fg:color_fg1"
format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"

[git_branch]
format = '[ $symbol $branch(:$remote_branch) ]($style)'
symbol = ""
style = "fg:color_fg1 bg:color_aqua"
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = "fg:color_fg1 bg:color_aqua"
deleted_style = "fg:color_fg1 bg:color_aqua"
disabled = false

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
modified = "●"
stashed = ""
untracked = ""
staged = ""
renamed = ""
deleted = ""
format = "[ $all_status $ahead_behind ]($style)"
style = "fg:color_fg1 bg:color_aqua"
