[settings]
idiomatic_version_file_enable_tools = ["python", "node"]

[tools]
# Languages and package managers
go = "1.26.1"
node = "24"
npm = "11.11.0"
ruby = "4.0.6"
yarn = "4.1.0"

# Tools
"aqua:neovim/neovim" = "0.12.5"
"github:kopecmaciej/vi-sql" = "v0.4.0" # https://github.com/kopecmaciej/vi-sql
"github:earendil-works/pi" = "v0.84.4" # https://github.com/earendil-works/pi
"npm:skills" = "1.4.3"
"github:agavra/tuicr" = "0.27.0" # https://github.com/agavra/tuicr
prettier = "3.8.1"
